auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2025-02-28
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 336h

compactor:
  retention_enabled: true
  delete_request_store: filesystem
  retention_delete_delay: 1h
  retention_delete_worker_count: 2

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h 