auth_enabled: false

server:
  http_listen_port: 3100
  log_level: debug

common:
  path_prefix: /loki  
  ring:
    instance_addr: loki
    kvstore:
      store: inmemory
  replication_factor: 1

schema_config:
  configs:
    - from: 2025-02-28 
      store: tsdb  
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /loki/chunks
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache

limits_config:
  allow_structured_metadata: true  
  reject_old_samples: true
  reject_old_samples_max_age: 336h  

compactor:
  working_directory: /loki/compactor  
  retention_enabled: true
  delete_request_store: filesystem
  retention_delete_delay: 1h
  retention_delete_worker_count: 2

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h  
