global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ['order-bouncer:8080']

  - job_name: 'order-bouncer'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['order-bouncer:8080']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']